
environment:
  NO_BLP_SERVICE: 1
  matrix:
  - julia_version: 1.4
  - julia_version: 1.9
  - julia_version: 1.10
  - julia_version: latest

matrix:
  allow_failures:
  - julia_version: latest

platform:
  - x64 # 64-bit

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
